spring:
  profiles:
    include: oauth
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

server:
  servlet:
    encoding:
      force-response: true
      charset: utf-8
      force: true

jwt:
  token:
    secret-key: qazwsxedcrfvtgbyhnujmiklop!@#$1234qazwsxedcrfvtgbyhnujmiklop;!@#$1234qazwsxedcrfvtgbyhnujmiklop;!@#$1234
  access-token:
    expire-length: 180000
  refresh-token:
    expire-length: 120960000

mail:
  address:
    admin: leemingyun@hotmail.co.kr